export const environment = {
  production: true,
  API_END_POINT: 'https://ptp-security-api.herokuapp.com/api',
  CONCEPT_BAJA: 'BAJA',
  CONCEPT_SUSPENSION: 'SUSPENSION',
  CONCEPT_FERIADO: 'FERIADO',
  CONCEPT_VACACIONES: 'VACACIONES',
  CONCEPT_ADELANTO: 'ADELANTO',
  CONCEPT_LIC_JUSTIFICADA: 'LIC_JUSTIFICADA',
  CONCEPT_LIC_NO_JUSTIFICADA: 'LIC_NO_JUSTIFICADA',
  CONCEPT_ART: 'ART',
  CONCEPT_CAPACITACION: 'CAPACITACIONES',
  CONCEPT_LIC_SIN_SUELDO: 'LIC_SIN_SUELDO'
};
